# Generated by Django 3.2 on 2021-05-11 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_followlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Date_Of_Birth', models.DateField(default=None)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Date_Of_Joining', models.DateField(auto_now=True)),
                ('Educational_Qualification', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=3)),
                ('creatorusr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creatorprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Date_Of_Birth', models.DateField(default=None)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Date_Of_Joining', models.DateField(auto_now=True)),
                ('learnerusr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learnerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
