# Generated by Django 3.2 on 2021-05-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210512_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowList',
        ),
    ]
