# Generated by Django 3.2 on 2021-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='date_posted',
            field=models.DateField(auto_now=True),
        ),
    ]
