# Generated by Django 3.2 on 2021-05-23 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('udemy', '0004_auto_20210507_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('learners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classesmodules', to=settings.AUTH_USER_MODEL)),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='udemy.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_completed', models.BooleanField(default=False)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='udemy.courses')),
                ('learners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
