# Generated by Django 3.2 on 2021-05-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_followlist'),
        ('udemy', '0005_classroom_classroommodules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='learners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.learnerprofile'),
        ),
        migrations.AlterField(
            model_name='classroommodules',
            name='learners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classesmodules', to='users.learnerprofile'),
        ),
    ]
