# Generated by Django 3.2 on 2021-05-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0008_reviews_reviewscreator_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewscreator',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='course',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='ReviewsCreator',
        ),
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
