# Generated by Django 3.2 on 2021-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy', '0011_reviewcourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='link',
            field=models.TextField(),
        ),
    ]
